#!/bin/bash

SOURCE="$1"
DEST="$2"

cat "${SOURCE}" | awk '
BEGIN {
    print("const char *vi_rc_string() { return");
}

{
    line = $0;
    if (substr(line, 1, 1) != "\"")
    {
        gsub(/\\/, "\\\\", line);
        gsub(/"/, "\\\"", line);
        print("\"" line  "\\n\"");
    }
}

END {
    print(";}");
}
' > "${DEST}"
